### ISSUE TITLE
meteorpad.com doesn't load when I am logged in

### ISSUE THREAD

**Issue by ryan-williams** [rissem/meteorpad#30]
When I go to [meteorpad.com](http://meteorpad.com/) I get redirected to a leaderboard example like [http://meteorpad.com/pad/qcjiZscmxBJrvYRXA/Leaderboard](http://meteorpad.com/pad/qcjiZscmxBJrvYRXA/Leaderboard) that never loads:

![](https://s3.amazonaws.com/f.cl.ly/items/1e0X091g1K0x0w2W3A3L/Screen%20Shot%202015-07-08%20at%2012.17.40%20PM.png)

I noticed that this started happening when I did the "Login with Meteor" flow.

If I go to [meteorpad.com](http://meteorpad.com/) in an incognito window it loads.

**Comment by ryan-williams** [comment]
Maybe transient issues? Now it seems to get further when I'm logged in but the console shows an error:

```
meteor --port=0.0.0.0:3000                                                                                                                                               
[[[[[ /app ]]]]]                                                                                                                                                         
                                                                                                                                                                         
=> Started proxy.                                                                                                                                                        
                                                                                                                                                                         
/home/meteor/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245     
                                                throw(ex);                                                                                                               
                                                      ^                                                                                                                  
Error: Unable to allocate ArrayBuffer.                                                                                                                                   
    at C_MINISAT (packages/logic-solver/minisat.js:3:1)                                                                                                                  
    at new MiniSat (packages/logic-solver/minisat_wrapper.js:19:1)                                                                                                       
    at new Logic.Solver (packages/logic-solver/logic.js:274:1)                                                                                                           
    at packages/constraint-solver/solver.js:533:1                                                                                                                        
    at Function.time (/home/meteor/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/profile.js:231:28)       
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver/solver.js:532:1)    ```
```

![](https://s3.amazonaws.com/f.cl.ly/items/1s0o3o3U0T190L460f2r/Screen%20Shot%202015-07-08%20at%2012.25.24%20PM.png)

**Comment by cwmp** [comment]
I am having the same issue right now. The console window doesnt stop loading and keeps spinning.
